import React from 'react';import {ChevronLeft,Home,History,Target,TrendingUp,Sparkles,UserRound,Info} from 'lucide-react';import {useNavigate,useLocation} from 'react-router-dom';import type {Goal} from '../domain/models';
export const Page=({children,className='',wide=false}:{children:React.ReactNode,className?:string,wide?:boolean})=><main className={`page ${wide?'wide':''} ${className}`}>{children}</main>;
export const Card=({children,className='',onClick}:{children:React.ReactNode,className?:string,onClick?:()=>void})=><section className={`card ${className}`} onClick={onClick}>{children}</section>;
export const Button=({children,onClick,outline=false,disabled=false}:{children:React.ReactNode,onClick?:()=>void,outline?:boolean,disabled?:boolean})=><button className={`btn ${outline?'btn-outline':''}`} disabled={disabled} onClick={onClick}>{children}</button>;
export const Field=({label,type='text',value,onChange,placeholder,error}:{label:string,type?:string,value:string,onChange:(v:string)=>void,placeholder?:string,error?:string})=><div className="field"><label>{label}</label><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>{error&&<small className="error">{error}</small>}</div>;
export const TopBar=({title,onBack,right}:{title:string,onBack?:()=>void,right?:React.ReactNode})=><header className="topbar"><div className="topbar-left">{onBack&&<button className="icon-btn" onClick={onBack}><ChevronLeft/></button>}<strong>{title}</strong></div>{right}</header>;
const navItems=[['home','Home',Home],['history','History',History],['goal','Goal',Target],['progress','Progress',TrendingUp],['ai_coach','AI Coach',Sparkles],['profile','Profile',UserRound]] as const;
export function BottomBar(){const nav=useNavigate(),loc=useLocation();return <nav className="bottom-bar">{navItems.map(([r,label,Icon])=><button key={r} className={loc.pathname.includes(r)?'active':''} onClick={()=>nav('/'+r)}><Icon/><span>{label}</span></button>)}</nav>}
export const AppShell=({children}:{children:React.ReactNode})=><div className="app-shell">{children}</div>;
export function GoalCard({goal,selected,onClick}:{goal:Goal;selected:boolean;onClick:()=>void}){return <Card className={`goal-card ${selected?'selected':''}`} onClick={onClick}><div className="goal-icon">{goal.id==='cancer_aware'?<img src="/cancer_awareness_logo.png"/>:goal.emoji}</div><div className="goal-copy"><b>{goal.title}</b><span>{goal.description}</span></div>{selected&&<span className="check">✓</span>}</Card>}
export const Stat=({label,value,target,unit,color='green'}:{label:string,value:number,target:number,unit:string,color?:string})=><div className="stat"><div className="stat-head"><span>{label}</span><b>{value}{unit} / {target}{unit}</b></div><div className="progress"><i className={color} style={{width:`${Math.min(100,value/target*100)}%`}}/></div></div>;
export const Chip=({children}:{children:React.ReactNode})=><span className="chip">{children}</span>;export const Empty=({title,text}:{title:string;text:string})=><div className="empty"><Info/><h3>{title}</h3><p>{text}</p></div>;